#include<bits/stdc++.h>
#include<unistd.h>
using namespace std;
int main()
{
     cout <<" \t\t\t\t\tWelcome!"<<endl;
      cout<< " \t\t\t\tYou are playing the game of.." << endl;
     cout<< " \t\t\t\tGuess the number!" << endl;
     cout<<endl;
     cout<<endl;
     cout<<endl;
     sleep(2);
    cout << "The rules for the game are:  " << endl;
    sleep(1);
    cout << "1.The number is randomly generated by the compiler!" << endl; sleep(1);
    cout << "2.You have to enter the number you think is generated!" << endl; sleep(1);
    cout << "3.Hints are provided to guide " << endl; sleep(1);
    cout<<endl;
    cout << "There are different levels of difficulty" << endl; sleep(1);

    cout<<"-------------------------------------------"<<endl;
    cout << "(1) Easy: Provides 10 chances" << endl; sleep(1);
    cout << "(2) Medium: Provides 5 chances" << endl; sleep(1);
    cout << "(3) Hard: Provides 2 chances" << endl;
     cout<<"-------------------------------------------"<<endl;
sleep(2);
    srand(time(0));
    int n=rand()% 100 + 1;;
    int num=0,l=0,chance;
    cout<<endl;
     sleep(1);
    cout<<"Enter your desired level of difficulty: ";
    cin>>l;
    switch (l)
    {
    case 1:
        chance=10;
        break;
    case 2:
        chance=5;
        break;
    case 3:
        chance=2;
        break;
    default:
        cout<<"Sorry! There is no such difficulty level: "; sleep(1);
        cout<<"Try Again!"<<endl; sleep(1);
        cout<<endl;
        return 0;
    }
    int i=0;
    while(i<chance)
    {
        // cout<<"-------------------------------------------"<<endl;
        cout<<"Guess the number between 1 to 100: ";
       // cout<<"-------------------------------------------"<<endl;
        cin>>num;
        cout<<endl;
    if(num>100)
    {

        cout<<"The number is outside the range!"<<endl;
        continue;
    }
    sleep(2);
    if(num==n)
    {
         cout<<"-------------------------------------------"<<endl;
        cout<<"Congrats!! Your guess was correct!"<<endl; sleep(1);
        cout<<"Thank You for playing!"<<endl;
         cout<<"-------------------------------------------"<<endl;
        cout<<endl;
       return 0;;
    }
   // sleep(2);
    else if(num<n)
    {
        cout<<"---------------------------------------------"<<endl;
        cout << "Oops! Your guess was incorrect!" << endl; sleep(1);
        cout << "Your guess is smaller than selected number" << endl; sleep(1);
        cout << "Choose a higher number & try again" << endl;
         cout<<"---------------------------------------------"<<endl;;
        cout<<endl;
        sleep(5);

    }
     else if(num>n)
    {
         cout<<"-------------------------------------------"<<endl;
        cout << "Oops! Your guess was incorrect!" << endl; sleep(1);
        cout << "Your guess is higher than selected number" << endl; sleep(1);
        cout << "Select a smaller value" << endl;
         cout<<"-------------------------------------------"<<endl;
        cout<<endl;
        cout<<endl;
        sleep(5);
    }
    i++;

    }
    cout<<endl;
    cout<<endl;
    cout<<"**********************************************"<<endl;
     cout<<"-------------------------------------------"<<endl;
     cout << "Sorry! You have lost the chances!!" << endl; sleep(1);
     cout<<"The correct answer was: "<<n<<endl; sleep(1);
    cout << "Better luck next time!" << endl; sleep(1);
    cout << "Thank You for playing" << endl;
     cout<<"-------------------------------------------"<<endl;
   cout<<"**********************************************"<<endl;
    sleep(2);

    cout<<endl;
    cout<<endl;
    return 0;



}
